emitting transfer in cash contract
verified-network/via-issuer pull request #28
Opened 2020-11-11 15:01 UTC by kallolborah

Please check emit functions in cash contract.

2020-11-11 16:58 UTC, kallolborah commented
Transfers are emitted in token.sol for bonds

2020-11-12 01:46 UTC, bonedaddy commented on contracts/Cash.sol
> +            else if(currency_in_deposit==""){
I dont think this comparison is needed

2020-11-12 01:47 UTC, bonedaddy commented on contracts/Token.sol
> +    event Transfer(address indexed from, address indexed to, uint tokens);
this contract inherits from ERC20 and doesnt need to redeclare the `Transfer` event.

2020-11-12 01:48 UTC, bonedaddy commented on contracts/Cash.sol
> +        //require(factory.getType(msg.sender) == "ViaCash");
i would add a todo comment indicating this needs to be fixed

2020-11-12 01:48 UTC, bonedaddy commented on contracts/Cash.sol
> +        //require(factory.getType(msg.sender) == "ViaCash" || factory.getType(msg.sender) == "ViaBond");
i would add a todo comment indicating this needs to be fixed

2020-11-12 01:48 UTC, bonedaddy commented on contracts/Cash.sol
> +        //require(factory.getType(msg.sender) == "ViaCash" || factory.getType(msg.sender) == "ViaBond");
i would add a todo comment indicating this needs to be fixed

2020-11-12 01:48 UTC, bonedaddy commented on contracts/Cash.sol
> -                emit Transfer(sender, receiver, tokens);
why remove the `Transfer` event here?

2020-11-12 01:49 UTC, bonedaddy commented on contracts/Cash.sol
> +    event Transfer(address indexed from, address indexed to, uint tokens);
This contract inherits from ERC20 and as such doesn't need to redeclare the `Transfer` event

2020-11-12 01:49 UTC, bonedaddy commented on contracts/Bond.sol
> +        //require(factory.getType(msg.sender) == "ViaCash" || factory.getType(msg.sender) == "ViaBond");
i would add a todo comment indicating this needs to be fixed

2020-11-12 01:49 UTC, bonedaddy requested changes
a few changes recommended

2020-11-12 01:55 UTC, kallolborah commented on contracts/Cash.sol
> +            else if(currency_in_deposit==""){
This is required because the block above may have a non empty currency_in_deposit value. If that’s the case, we don’t want this block to overwrite it

2020-11-12 01:56 UTC, kallolborah commented on contracts/Token.sol
> +    event Transfer(address indexed from, address indexed to, uint tokens);
Okay, I am not sure we have the transfer event declared in our ERC20 contract, if we do, please remove

2020-11-12 01:59 UTC, kallolborah commented on contracts/Cash.sol
> +    event Transfer(address indexed from, address indexed to, uint tokens);
Okay please remove if the erc20 contract has the transfer event

2020-11-12 02:05 UTC, kallolborah commented on contracts/Cash.sol
> -                emit Transfer(sender, receiver, tokens);
Transfer has been removed here because this function is called post issue() in which transfer is emitted.

2020-11-12 02:10 UTC, bonedaddy commented on contracts/Cash.sol
> +    event Transfer(address indexed from, address indexed to, uint tokens);
```suggestion
```

2020-11-12 02:12 UTC, bonedaddy commented on contracts/Token.sol
> +    event Transfer(address indexed from, address indexed to, uint tokens);
It is because `Token` inherits https://github.com/verified-network/via-issuer/blob/master/contracts/erc/ERC20 which declares the Transfer event here https://github.com/verified-network/via-issuer/blob/master/contracts/erc/ERC20.sol#L30

2020-11-12 02:13 UTC, bonedaddy commented on contracts/Token.sol
> +    event Transfer(address indexed from, address indexed to, uint tokens);
```suggestion
```

2020-11-12 02:14 UTC, bonedaddy approved these changes
Looks good

2020-11-12 02:19 UTC, merged